# Header

menu:
  ä¸»é¡µ: /
  éšç¬”: /categories/essay/
  é¡¹ç›®: /categories/project/
  

# SubNav
subnav:
  github: "http://github.com/yvon-shong"
  # weibo: "http://weibo.com/yiwenggogo"
  bilibili: https://space.bilibili.com/6083595
  zhihu: "http://zhihu.com/people/yvon-shong"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:yvon@shong.win"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
url: http://www.shong.win/blog
root: /blog/

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: more
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: false
# æ•°å­¦å…¬å¼
mathjax: true
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# æ‰“èµ
# è¯·åœ¨éœ€è¦æ‰“èµçš„æ–‡ç« çš„mdæ–‡ä»¶å¤´éƒ¨ï¼Œè®¾ç½®å±æ€§reward: true

# æ‰“èµåŸºç¡€è®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'å–ä¸€æ¯ java'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo438owfuj2083083jsc.jpg
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo43wmet4j20gz0gvn07.jpg

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#ä½ çš„å¤´åƒurl
avatar: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo5ta11dqj226i26jb0m.jpg

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#æ˜¯å¦å¼€å¯å¤šè¯´è¯„è®ºï¼Œå¡«å†™ä½ åœ¨å¤šè¯´ç”³è¯·çš„é¡¹ç›®åç§° duoshuo: duoshuo-key
#è‹¥ä½¿ç”¨disqusï¼Œè¯·åœ¨åšå®¢configæ–‡ä»¶ä¸­å¡«å†™disqus_shortnameï¼Œå¹¶å…³é—­å¤šè¯´è¯„è®º
# duoshuo: shong


# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4acaa8'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: true

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  aboutme: 'å…³äºæˆ‘'
  friends: "é“¾æ¥"

aboutme: è‡ªåŠ¨é©¾é©¶ä»ä¸šè€…ğŸšš | TuSimple<br>å¾®è½¯å¤§æ³•ä¼ æ•™å£«â›ªï¸ | MSP <br>æ—©ç¨»ç”°ä¿®å£«ğŸŒ¸ | Waseda University<br>vloggerğŸ¥ <br>è¿˜æœ‰å°‘å¹´çƒ­å¿±ğŸ™‹ğŸ»â€â™‚ï¸

friends: 
  TuSimple | å›¾æ£®æœªæ¥: http://tusimple.ai
  Waseda University | æ—©ç¨»ç”°å¤§å­¦: http://www.waseda.jp
  Southeast University | ä¸œå—å¤§å­¦: http://www.seu.edu.cn
  Chengdu No.7 Middle High School | æˆéƒ½ä¸ƒä¸­: http://www.cdqz.net
  PaoPaoRobot | æ³¡æ³¡æœºå™¨äºº: http://paopaorobot.org/
  Microsoft Student Partner | å¾®è½¯æ ¡å›­ç²¾è‹±: https://studentpartners.microsoft.com/
  ippclub | I++ä¿±ä¹éƒ¨: http://ippclub.org/
  Appveyor: https://ci.appveyor.com/project/shong/yvon-shong-github-io
