# Header

menu:
  ä¸»é¡µ: /
  æŠ€æœ¯: /categories/tech/
  éšç¬”: /categories/essay/
  

# SubNav
subnav:
  bilibili: "https://space.bilibili.com/6083595"
  zhihu: "http://zhihu.com/people/yvonshong"
  github: "http://github.com/yvonshong"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:yvon@shong.win"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
# url: http://www.yvonshong.com/blog
# root: /blog/
root: /

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: more
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: false
# æ•°å­¦å…¬å¼
mathjax: true
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# Word Count
word_count: true

# æ‰“èµåŸºç¡€è®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'äººæ°‘å¸ç‰ˆçš„èµ'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
# alipay: https://raw.githubusercontent.com/yvonshong/picbed/refs/heads/master/8jJiNGcROCedwEA.png
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: https://raw.githubusercontent.com/yvonshong/picbed/refs/heads/master/It31kXcofTA9UB2.png

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 1
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'æ— ç›®å½•'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: https://raw.githubusercontent.com/yvonshong/picbed/refs/heads/master/HAbatdcnuM37PKf.png

#ä½ çš„å¤´åƒurl
avatar: https://raw.githubusercontent.com/yvonshong/picbed/refs/heads/master/HAbatdcnuM37PKf.png

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
changyan_appid: false
changyan_conf: false

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: ''          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4acaa8'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: true

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  aboutme: 'å…³äºæˆ‘'
  friends: 'å‹é“¾'

aboutme: è‡ªåŠ¨é©¾é©¶ä»ä¸šè€…ğŸ¤– | Hesai Tech<br>æ—©ç¨»ç”°ä¿®å£«ğŸŒ¸ | Waseda University<br>vloggerğŸ¥ | Bç«™id yvonshong <br>å°‘å¹´çƒ­å¿±ğŸ™‹ğŸ»â€â™‚ï¸

friends: 
  çŸ¥ä¹ä¸“æ  | è‡ªå¾‹èµ°è¡Œ  : https://zhuanlan.zhihu.com/jiritsu-soko
  ç¦¾èµ›ç§‘æŠ€ | Hesai Tech: https://www.hesaitech.com
  å›¾æ£®æœªæ¥ | TuSimple: https://tusimple.com
  æ—©ç¨»ç”°å¤§å­¦ | Waseda University: http://www.waseda.jp
  ä¸œå—å¤§å­¦ | Southeast University: http://www.seu.edu.cn
  æˆéƒ½ä¸ƒä¸­ | Chengdu No.7 Middle High School: http://www.cdqz.net
  æ³¡æ³¡æœºå™¨äºº | PaoPaoRobot: http://paopaorobot.org/
  å¾®è½¯æ ¡å›­ç²¾è‹± | Microsoft Student Partner: https://studentambassadors.microsoft.com/
  # Yvon's Horizon | çŸ¥ä¹ä¸“æ : https://zhuanlan.zhihu.com/yvon-horizon
  # å¾®è½¯å¤§æ³•å¥½ | çŸ¥ä¹ä¸“æ : https://zhuanlan.zhihu.com/microsoft
  # vlog åˆè¾‘ | bilibili: https://space.bilibili.com/6083595
  # Wondergate | å¥‡é˜µç§‘æŠ€: http://wondergate.io/
  # ci123 | è‚²å„¿ç½‘: http://ippclub.org/
  # asamaedu | æµ…é—´ç•™å­¦: http://asamaedu.com
  # ippclub | I++ä¿±ä¹éƒ¨: http://ippclub.org/
